module.exports = `{
  "systemCode": "monkeycode",
  "policyDescription": "Generated by AWS Policy Generator",
  "performTestRun": "true",
  "requireS3": {
    "artefacts": true,
    "application": false
  },
  "requireLambda": true,
  "requireApiGateway": true,
  "requireDynamo": false,
  "requireKinesis": false,
  "requireCloudformation": {
    "changeRequestSetName": "Serverless-2016-10-31",
    "required": true,
    "changeRequestRequired": true
  }
}`
